;;;
;;; Machine Generated By /bisos/git/auth/bxRepos/bisos/bsip4/bin/doomPkgsProfile.sh::vis_doomPkgsStdout on 20220528223625
;;; Input= /bisos/blee/29f/doom-main-blee3/.local/straight/repos
(
 (adaptive-wrap
  :repoUrl "https://github.com/emacs-straight/adaptive-wrap.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (add-node-modules-path
  :repoUrl "https://github.com/codesuki/add-node-modules-path.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (a.el
  :repoUrl "https://github.com/plexus/a.el.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (alert
  :repoUrl "https://github.com/jwiegley/alert.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
)
